name: API-Builder API-Mock up

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release: 
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run npm ci, npm test
      working-directory: ${{env.workingDirectory}}
      env:
        LOG_LEVEL: INFO
        CI: true
      run: | 
        npm ci
        npm run build --if-present
        npm test
  publish:
    if: github.event.action == 'published'
    env:
      workingDirectory: 'elk-traffic-monitor-api'
    needs: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Publish Docker image
      uses: elgohr/Publish-Docker-Github-Action@2.13
      with:
        name: cwiechmann/api-mockup
        workdir: ${{env.workingDirectory}}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        snapshot: true

