name: Import mocked entities

on:
  workflow_dispatch:
    inputs:
      apimHost:
        description: "The API-Manager Hostname"
        required: true
      apimUsername:
        description: "The API-Manager Username"
        required: true
      apimPassword:
        description: "The API-Manager Password"
        required: true
      apimPort:
        description: "The API-Manager Port"
        required: true

jobs:
  importMockedEntities:
    name: Import Mocked Entities
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Check out
      - name: Import Orgs
        uses: Axway-API-Management-Plus/apim-cli-github-action@v1.5.1
        with:
          apimHostname: ${{ github.event.inputs.apimHost }}
          apimPort: "443"
          apimUsername: ${{ github.event.inputs.apimUsername }}
          apimPassword: ${{ github.event.inputs.apimPassword }}
          apimExtraArgs: '-port ${{ github.event.inputs.apimPort }} -force -returnCodeMapping 10:0'
          orgDirectory: 'apim-cli-data/Organizations'
      - name: Import Applications
        uses: Axway-API-Management-Plus/apim-cli-github-action@v1.5.1
        with:
          apimHostname: ${{ github.event.inputs.apimHost }}
          apimPort: "443"
          apimUsername: ${{ github.event.inputs.apimUsername }}
          apimPassword: ${{ github.event.inputs.apimPassword }}
          apimExtraArgs: '-port ${{ github.event.inputs.apimPort }} -force -returnCodeMapping 10:0'
          orgDirectory: 'apim-cli-data/ClientApps'
      - name: Import APIs
        uses: Axway-API-Management-Plus/apim-cli-github-action@v1.5.1
        with:
          apimHostname: ${{ github.event.inputs.apimHost }}
          apimPort: "443"
          apimUsername: ${{ github.event.inputs.apimUsername }}
          apimPassword: ${{ github.event.inputs.apimPassword }}
          apimExtraArgs: '-port ${{ github.event.inputs.apimPort }} -force -returnCodeMapping 10:0'
          orgDirectory: 'apim-cli-data/APIs'
        env:
          BACKEND_HOST: 'http://mocked-apis:8280'

  validateCertificates:
    name: Validate certificates
    runs-on: ubuntu-latest
    steps:
      - name: Check certificates
        uses: Axway-API-Management-Plus/apim-cli-github-action@v1.5.1
        with:
          apimHostname: ${{ github.event.inputs.apimHost }}
          apimPort: "443"
          apimUsername: ${{ github.event.inputs.apimUsername }}
          apimPassword: ${{ github.event.inputs.apimPassword }}
          apimCLICommand: 'api check-certs'
          apimExtraArgs: '-days 60'