name: Import mocked APIs

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      apimHost:
        description: "The API-Manager Hostname"
        required: true
      apimUsername:
        description: "The API-Manager Username"
        required: true
      apimPassword:
        description: "The API-Manager Password"
        required: true
      apimPort:
        description: "The API-Manager Port"
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Import Mocked APIs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check certificates
        uses: Axway-API-Management-Plus/apim-cli-github-action@v1.5.1
        with:
          apimHostname: ${{ github.event.inputs.apimHost }}
          apimPort: "443"
          apimUsername: ${{ github.event.inputs.apimUsername }}
          apimPassword: ${{ github.event.inputs.apimPassword }}
          apimCLICommand: 'api check-certs'
          apimExtraArgs: '-days 60'
      - name: Import Organizations
        uses: Axway-API-Management-Plus/apim-cli-github-action@v1.5.1
        with:
          apimHostname: ${{ github.event.inputs.apimHost }}
          apimPort: "443"
          apimUsername: ${{ github.event.inputs.apimUsername }}
          apimPassword: ${{ github.event.inputs.apimPassword }}
          apimExtraArgs: '-port ${{ github.event.inputs.apimPort }} -force -returnCodeMapping 10:0'
          orgDirectory: 'apim-cli-data/Organizations'
        env:
          BACKEND_HOST: 'http://mocked-apis:8280'
