name: Import mocked APIs

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      apimHost:
        description: "The API-Manager Hostname"
        required: true
      apimUsername:
        description: "The API-Manager Username"
        required: true
      apimPassword:
        description: "The API-Manager Password"
        required: true
      apimPort:
        description: "The API-Manager Port"
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Axway APIM-CLI Github Action
        uses: Axway-API-Management-Plus/apim-cli-github-action@v1.5.1
        with:
          apimHostname: 'manager.customer.com'
          apimUsername: 'apiadmin'
          apimPassword: '1234567890'
          apimExtraArgs: '-port 443 -force -returnCodeMapping 10:0'
          apiDirectory: 'axway/api-management/APIs'
        env:
          BACKEND_HOST: 'http://mocked-apis:8280'
